Bs 312/clustering arucos
PSBPOSAS/dji-asdk-to-python pull request #145
Opened 2023-06-06 14:44 UTC by Dhliv

Improvement in visual landing algorithm:

- Implemented new algorithm to change ISO relying on brightness level on image.
- Developed algorithm of clustering for arucos to prevent the drone going haywire and establish a right place to direct it to land.
- Developed funneling zone where the drone could direct itselft towards detected aruco every time that it sees it. Outside this funnel zone, drone wouls use clustering algorithm to know where to go to make landing.
- Code refactored
- Added documentation
- Added type annotations

2023-06-06 17:40 UTC, davidbo99 requested changes

2023-06-08 00:15 UTC, davidbo99 requested changes
Algunos otros pequeños comentarios.

2023-06-08 00:15 UTC, davidbo99 commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +            return
No deberia tener un return si se supone que no retorna nada. Se puede mejorar los condicionales.
```suggestion
    self._is_iso_changing = True

    if not (self.is_current_iso_suitable(frame) and force_change):
        self._change_iso(frame)
```

2023-06-08 00:15 UTC, davidbo99 commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +            return
Esta sugerencia es para la funcion completa

2023-06-08 00:15 UTC, davidbo99 commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +    def getIsIsoChanging(self) -> bool:
Hace falta el decorador `@property`.

2023-06-08 00:15 UTC, davidbo99 commented on dji_asdk_to_python/precision_landing/test.py
Este archivo deberia estar ubicado en un modulo de tests. Igual seria bueno entender el proposito de este.

2023-06-08 00:15 UTC, davidbo99 requested changes
Algunos otros pequeños comentarios.

2023-06-08 13:53 UTC, perqueza72 commented on dji_asdk_to_python/battery/battery_state.py
> +        val: 'int | str | float' = message.get(method_name, None)
It should be better use message[method_name]. It notify to user that this method not exists instantly. Another good way is use a custom throw to make easier detect what is the cause of the error.

2023-06-08 13:53 UTC, perqueza72 commented on dji_asdk_to_python/flight_controller/location_coordinate_2d.py
> +    def __eq__(self, __value: 'LocationCoordinate2D') -> bool:
EPSILON in used only in this scope. Either be more specific with the name (because the file is so long and could produce an error or misconception) or create this constant into __eq__ method.

2023-06-08 13:53 UTC, perqueza72 commented on dji_asdk_to_python/flight_controller/location_coordinate_2d.py
> +        cond: bool = abs(self.latitude - __value.latitude) < EPSILON
```
if (abs(self.latitude - __value.latitude) >= EPSILON):
 return False
```
This way is more readable. (Check if means the same)

Do the same with the rest.

2023-06-08 13:53 UTC, perqueza72 commented on dji_asdk_to_python/precision_landing/image_brightness.py
> +    """
Docstring :(

2023-06-08 15:19 UTC, davidbo99 commented on dji_asdk_to_python/battery/battery_state.py
> +        val: 'int | str | float' = message.get(method_name, None)
It will not notify the user, it will crash the instance with KeyError exception. Using the get function is always a better practice, specially when having default values that define the appropiate behaviour of the function. You could combine this by using the default value as None, and raising a custom exception but that is not necessary if the behaviour is well defined with None values.

2023-06-08 15:26 UTC, Dhliv commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +    def getIsIsoChanging(self) -> bool:
Acabo de leerlo, pero no me agrada en lo absoluto el decorador de property, me parece mucho mejor tener getters y setters de forma explícita.

2023-06-08 15:27 UTC, Dhliv commented on dji_asdk_to_python/precision_landing/test.py
Archivo eliminado. Tenía el propósito de comprender cómo actuaba el ISOChanger viendo directamente del dron

2023-06-08 15:57 UTC, davidbo99 commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +    def getIsIsoChanging(self) -> bool:
Este decorador hace las clases mas legibles y aporta a la mantenibilidad. Ademas hace de fachada para las propiedades protegidas por convencion. Igual se tendran getters y setters de forma explicita, solo que con el nombre de la propiedad. Que no te agrada de las propiedades?

2023-06-08 16:06 UTC, davidbo99 commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +            return
El return solo rompe la funcion. Es una funcion vacia que cambia el ISO bajo ciertas condiciones. Segun como esta escrita, veo que hay mayor complejidad temporal ya que estas evaluando mas instrucciones... Esta funcion puede salir en menos lineas de codigo, mas legible, y sin la necesidad de incluir un return porque igual si no entra en el if, no ocurrira la siguiente linea.

2023-06-08 16:11 UTC, Dhliv commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +    def getIsIsoChanging(self) -> bool:
Que no se invocan las funciones de forma explícita, es necesario hacer _**obj.property**_ tanto para cambiar como para obtener la propiedad, y eso, pese a que es seguro por el decorator de property, no me agrada en lo absoluto porque todo mi ser me grita lo contrario (debido a la programación de bajo nivel). En ese sentido, ya que las funciones setter y getter de igual forma se tienen que declarar de forma explícita, prefiero que sus invocaciones lo sean también, para un programador es mas fácil asimilar los getters y setters de esa forma

2023-06-16 14:28 UTC, Dhliv commented on dji_asdk_to_python/precision_landing/ISOChanger.py
> +            return
El condicional no sirve, porque force change no siempre es True, a veces el cambio no debe ser forzado y en ese caso, la función no cumpliría con lo cometido.

2023-07-14 18:48 UTC, davidbo99 approved these changes

2023-07-14 20:05 UTC, merged